{
    "config": {
        "error": {
            "invalid_auth": "Virheellinen todennus",
            "unknown": "Odottamaton virhe"
        },
        "step": {
            "user": {
                "data": {
                    "api_key": "API-avain"
                },
                "description": "Pyyd\u00e4 API-tili\u00e4 osoitteessa {api_account_url}."
            }
        }
    },
    "options": {
        "error": {
            "invalid_auth": "Virheellinen todennus",
            "unknown": "Odottamaton virhe"
        }
    }
}